// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://azwypcylkfktuambrfvh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF6d3lwY3lsa2ZrdHVhbWJyZnZoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQzNjI4MTUsImV4cCI6MjA0OTkzODgxNX0.jsJYBNKOL24TsrvtJefCRoLagoLmQs_jQQ--WYi2PEU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);